[theme]
# W&M Primary Green
primaryColor = "#115740"

# Light/White Background
backgroundColor = "#FFFFFF"

# Very faint grey/green for secondary boxes
secondaryBackgroundColor = "#F4F6F5"

# Dark Charcoal for readable text
textColor = "#222222"

font = "sans serif"